[Appearance]
color_scheme_path=/home/naga/.config/qt5ct/colors/Catppuccin-Mocha.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=kvantum

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x2\x31\0\0\x2\x90\0\0\0\0\0\0\0\0\0\0\x3\xb3\0\0\x2\x90\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x2\x31\0\0\x2\x90)
